# Copyright 2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

.DEFAULT_GOAL := test

INTERFACES := ../storeclient/istoreclient.go
INTERFACES += ../decoder/idecoder_manager.go

MOCKPKG := mocks

include ../../mk/common.mk
include ../../mk/pkg.mk
include ../../mk/lint.mk
include ../../mk/test.mk
