# Copyright 2021 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

SUBDIR := arangodbendorsements
SUBDIR += opapolicyengine
SUBDIR += sqliteendorsements
SUBDIR += sqlitepolicy
SUBDIR += token-dice
SUBDIR += token-psa
SUBDIR += trustanchorstore-sqlite

include ../mk/subdir.mk
