# Copyright 2021 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../bin/arangodb-endorsement-store
GOPKG := arangodbendorsements
SRCS := main.go
INTERFACES := store.go
MOCKPKG := main


include ../../mk/common.mk
include ../../mk/plugin.mk
include ../../mk/lint.mk
include ../../mk/test.mk
