@startuml
skinparam rectangle {
    ' these params allow any rectangle with the label stereotype to be displayed just as text
    BackgroundColor<<label>> White
    BorderColor<<label>> White
    Shadowing<<label>> False
}
hide stereotype  
'skinparam nodesep 5
skinparam ranksep 5


title "Multiple products from the same MF"

rectangle 1h1f as "
Product 1H1F
----
TA ID (U or G)
HW Group ID 1
[FWa, FWb, FWc, FWd]
"
rectangle 2h1f as "
Product 2H1F
----
TA ID (U or G)
HW Group ID 2
[FWa, FWb, FWc, FWd]
"

rectangle 1h2f as "
Product 1H2F
----
TA ID (U or G)
HW Group ID 1
[FWa, FWb, FWx, FWy]
"

rectangle 2h2f as "
Product 2H2F
----
TA ID (U or G)
HW Group ID 2
[FWv, FWw, FWx, FWy]
"

1h1f -r-> 2h1f : HW GID difference, FW same. e.g. performance variants of the same product
1h1f -d-> 1h2f : Use a common HW platform (& partial FW commonality) for multiple products. Usage may not overlap.
1h1f -d-> 2h2f : No measurable overlap in HW or FW even if functionally equivalent to user i.e. Don’t Care, Treat as separate
2h1f -[hidden]d-> 2h2f
@enduml