@startuml
skinparam rectangle {
    ' these params allow any rectangle with the label stereotype to be displayed just as text
    BackgroundColor<<label>> White
    BorderColor<<label>> White
    Shadowing<<label>> False
}
hide stereotype  
'skinparam nodesep 5
skinparam ranksep 5


title "Background - Device Models"

rectangle urot1 as "Unique TA ID
HW Group ID
[FW Components]
"
rectangle urot1lab<<label>> as "PSA
"
urot1 -[hidden]d-> urot1lab

rectangle  grot1 as "Group TA ID
HW Group ID
[FW Components]
"
rectangle grot1lab<<label>> as "PSA older Android
"
grot1 -[hidden]d-> grot1lab

rectangle urot2 as "Unique TA ID
'--HW Group ID--
' strikeout above not rendering correctly
[FW Components]
"
rectangle urot2lab<<label>> as "DICE (Android BCC)
AMD SEV (FW Ver only)
Intel SGX (FW ver only)
TPM 
"
urot2 -[hidden]d-> urot2lab

rectangle grot2 as "Group TA ID
'--HW Group ID--
' strikeout above not rendering correctly
[FW Components]
"
rectangle grot2lab<<label>> as "Older Android
"
grot2 -[hidden]d-> grot2lab


rectangle assump<<label>> as "FW component list is only
those relevant to TCB.
Anything else falls into ‘workload’
which may also be part of the
attestation coverage but 
may involve an additional 
supply chain role.
"
urot2 -[hidden]r-> assump


urot1 --[hidden]r-> grot1
urot1lab --[hidden]d-> urot2
urot2 --[hidden]r-> grot2
grot1lab --[hidden]d-> grot2
@enduml


' http://www.plantuml.com/plantuml/png/jLFDJjjC5DtVfpZA1bWOwOlqxH0YE42pY8eK2fKGYuddOeyocUlEZ8EYgXAFqRuUJz8nRaYAGLKNtLbpvjnxVZmd8IeVcwKb2WlZQkNL4fwBg5nf6Ly904vLiIYzD4xdOiKV7LarPtjyZ9lAHEwkYDVituLdbTBoO5ov1S-L3KpVg3AQ4I9xbhYk6Q2zhH8dcWFN-7zNdNABxemeccWPWwr0P1ZpoXICQQBQC23QkccynF-W0WQVdFdICAv6c8pfmmqk4hbkls_FRv3BiXR7BeOx6hoc9_bR3-seozc8ydo40NNZizlaIBExqzdn2sLN1SeN6TtQlrDHlgS2OZLxZ9psOdJYb7qz6_BhL8RzLFQoR4TIbj4UGlHcmT94gBci64uYFBkqDJMBGdmxrAx_6EAm9xyDS7ysRIS-RoaYn66ohEraV43ZINw6_L_6S9hd1pIQZZ4xkyP-MdND7kBi-e0cBhB5xEBpy_dgvVpgSWhg2Xhs2shbqAk4Xzj-_cqUvPjvVEnLsLE-8TAkT1L2iwn_dvMM5vlbi2P4cF2S2yLA0iEpvPLAM1HSvQU7D7BhMBKEs2RuNbaRO5n2dnw_FuXVM57wwV47FLIcgB1KQoWR17D6hNo4t2DMJ2f63b558oxjJrseaZ5l8gXb6BSIks8e1wMrQMyf2mfDNTirYaeP1o-M3_kr-MI-yqcqUNDRSFEJq-Rf8UiNtetiqn9Ilathm1DskbdQdm00

