# Copyright 2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

SUBDIR := decoder
SUBDIR += plugins
SUBDIR += cmd
SUBDIR += storeclient
SUBDIR += api

include ../mk/subdir.mk
