# Copyright 2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

SUBDIR += common
SUBDIR += corim-psa-decoder
SUBDIR += corim-tpm-enacttrust-decoder

include ../../mk/subdir.mk
