# Go Linters - GitHub Actions
name: linters
on: []
jobs:
  # Check linters on latest-ubuntu with go version "1.17.2"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.18"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install mockgen
      run: |
        go install github.com/golang/mock/mockgen@v1.6.0
    - name: Install golangci-lint
      run: |
        go version
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.47.0
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: protoc-gen deps
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
        go install github.com/mitchellh/protoc-gen-go-json@latest
    - name: Run required linters in .golangci.yml plus hard-coded ones here
      run: make -w GOLINT=$(go env GOPATH)/bin/golangci-lint lint
    - name: Run optional linters (not required to pass)
      run: make -w GOLINT=$(go env GOPATH)/bin/golangci-lint lint-extra
