# Copyright 2021 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

.DEFAULT_GOAL := test

GOPKG := github.com/veraison/veraison/kvstore

include ../mk/common.mk
include ../mk/pkg.mk
include ../mk/lint.mk
include ../mk/test.mk
